platform: linux
image: docker:///cloudfoundry/cli-ci

inputs:
- name: final-cli
  path: cli
- name: cli-private
- name: temp-cli
  path: gopath/src/github.com/cloudfoundry/cli

params:
  GPG_KEY:
  KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_ACCESS_KEY_ID:
  AWS_BUCKET_NAME: cf-cli-debian

run:
  path: bash
  args:
  - -c
  - |
    set -ex
    gpg --import <(echo "${GPG_KEY}")
    export DEBIAN_FRONTEND=noninteractive

    mkdir installers

    pushd cli
      git remote set-url origin https://github.com/cloudfoundry/cli.git
      git fetch --tags
      release_tag=$( git show-ref --tags -d | grep $(git rev-parse HEAD) | cut -d'/' -f3 | egrep 'v[0-9]' | cut -d'v' -f2 )
    popd

    if [ -z "${release_tag}" ]; then
      echo "Expected the commit that triggered this build to be tagged." >&2
      exit 1
    fi

    filename_regex="cf-cli(-installer)?([-_0-9a-z]+)?(\.[a-z]+)?"
    pushd installers
      VERSIONS="6.0.2 6.1.0 6.1.1 6.1.2 6.2.0 6.3.0 6.3.1 6.3.2 6.4.0 6.5.0 6.5.1 6.6.0 6.6.1 6.6.2 6.7.0 6.8.0 6.9.0 6.10.0 6.11.0 6.11.1 6.11.2 6.11.3 6.12.0 6.12.1 6.12.2 6.12.3 6.12.4 6.13.0 6.14.0 6.14.1 6.15.0 6.16.0 6.16.1 6.17.0 6.17.1 6.18.0 6.18.1 6.19.0 6.20.0 6.21.0"
      echo $VERSIONS | xargs -n1 -P 10 -I{} curl -L -o cf-cli-installer_{}_i686.deb 'https://cli.run.pivotal.io/stable?release=debian32&version={}'
      echo $VERSIONS | xargs -n1 -P 10 -I{} curl -L -o cf-cli-installer_{}_x86-64.deb 'https://cli.run.pivotal.io/stable?release=debian64&version={}'
    popd

    cat >> $HOME/.gnupg/gpg.conf <<EOF
    personal-digest-preferences SHA256
    cert-digest-algo SHA256
    default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
    EOF

    deb-s3 upload installers/*.deb --preserve-versions --sign=${KEY_ID} --bucket=${AWS_BUCKET_NAME}

